-- Seed Lean Pylon ticket and NPS feature requests as signals and insight cards

insert into signals (account_name, source, source_id, feature_request, verbatim_quote, signal_date) values
('Lean', 'pylon', 'lean-3669', 'Receipt preview in expenses view without clicking into each expense', 'It would be great if in the Expenses view, there was a preview of the receipts, instead of having to click into each one', '2025-11-01T00:00:00Z'),
('Lean', 'pylon', 'lean-3668', 'Custom expense categories (e.g. Relocation Expense)', 'Are we able to add an expense category please? Relocation Expense. Or is it a case that categories are fixed?', '2025-11-01T00:00:00Z'),
('Lean', 'pylon', 'lean-4728', 'Multiple receipts upload for a single expense claim', 'is it possible for employees to upload multiple receipts for a single expense claim?', '2025-12-01T00:00:00Z'),
('Lean', 'pylon', 'lean-5110', 'Revert rejected expense back to employee for correction and re-submission', 'is there a way to revert a rejected expense back to the employee to correct and re-submit? or do they need to re-create the expense from scratch', '2026-01-15T00:00:00Z'),
('Lean', 'pylon', 'lean-5067', 'Allow employees to submit expense claims for future dates', 'is there a way to enable employees to submit expense claims for future dates?', '2026-01-13T00:00:00Z'),
('Lean', 'pylon', 'lean-4787', 'Expense review workflow improvements', 'Are there any plans to make the Expenses review process better? Some things I have seen on other platforms that I would love to see here', '2025-12-01T00:00:00Z'),
('Lean', 'pylon', 'lean-4694', 'Bulk compensation update for multiple employees', 'is there a way to do bulk update for compensation?', '2025-12-01T00:00:00Z'),
('Lean', 'pylon', 'lean-3513', 'HiBob and Cercli integration', 'do we have an integration between bob and cercli?', '2025-10-01T00:00:00Z'),
('Lean', 'pylon', 'lean-4610', 'Wafeq accounting integration', 'Wafeq-Cercli Integration Timelines - when can we expect a direct integration with Wafeq for payroll and expense accounting?', '2025-12-01T00:00:00Z'),
('Lean', 'pylon', 'lean-3356', 'KSA payrun summary report in Saudi Riyals (SAR)', 'Can we have a Payrun summary for the KSA payroll that will show in Saudi Riyals? or if theres a way to see amounts in SAR', '2025-10-01T00:00:00Z'),
('Lean', 'pylon', 'lean-5072', 'GPSSA pension scheme integration (similar to GOSI for KSA)', 'can we incorporate GPSSA in the system like what we do in GOSI for KSA?', '2026-01-13T00:00:00Z'),
('Lean', 'pylon', 'lean-1670', 'Outstanding EOSB provision visibility on the platform', 'Is there a way to see the outstanding EOSB provision we should be accounting for on the platform?', '2025-07-01T00:00:00Z'),
('Lean', 'pylon', 'lean-5483', 'Probation period completion notification alerts', 'we stopped getting notifications about employees who are about to complete their probation period. Please add a notification', '2026-01-15T00:00:00Z'),
('Lean', 'pylon', 'lean-5828', 'Admin ability to download payslips on behalf of employees', 'Downloading Payslips on Behalf of Employee - admin requested ability to download employee payslips', '2026-02-15T00:00:00Z'),
('Lean', 'pylon', 'lean-5954', 'TRN number on Cercli invoices', 'Adding TRN number to attached invoices - please add our TRN and correct address in the invoices', '2026-02-20T00:00:00Z'),
('Lean', 'pylon', 'lean-6238', 'Entity-level user role configuration for payroll management', 'Entity-level user role configuration for payroll management - need to configure roles per entity not just globally', '2026-05-10T00:00:00Z'),
('Lean', 'pylon', 'lean-6106', 'Full Egypt payroll support with direct payment (not bank file only)', 'Payroll Compliance and Support in Egypt - right now payments need to be made on our side with Cercli providing the bank file only', '2026-05-01T00:00:00Z'),
('Lean', 'pylon', 'lean-3188', 'ADCB bank integration for direct payroll payouts', 'our ProdEng team is ready to build an integration with ADCB Payouts functionality - Integration request for ADCB Payouts', '2025-09-01T00:00:00Z'),
('Lean', 'pylon', 'lean-nps-1', 'Split expense and salary pay runs into separate runs', 'Splitting Expense and Salary pay runs - right now they are combined and we want them separate', '2026-06-09T00:00:00Z'),
('Lean', 'pylon', 'lean-nps-2', 'Equipment sourcing and procurement for remote employees', 'Equipment sourcing/procurement (especially for remote employees) - this is missing from the platform', '2026-06-09T00:00:00Z'),
('Lean', 'pylon', 'lean-nps-3', 'AI-powered expense review, editing and querying', 'More AI functionality to help review/edit/query expense submissions', '2026-06-09T00:00:00Z')
on conflict (source, source_id, feature_request) do nothing;

insert into insight_cards (source_id, title, body, status, type, related_account, source, signal_date) values
('lean-3669', 'Receipt preview in expenses view without clicking into each expense', 'It would be great if in the Expenses view, there was a preview of the receipts, instead of having to click into each one', 'pending', 'new_signal', 'Lean', 'pylon', '2025-11-01T00:00:00Z'),
('lean-3668', 'Custom expense categories (e.g. Relocation Expense)', 'Are we able to add an expense category please? Relocation Expense. Or is it a case that categories are fixed?', 'pending', 'new_signal', 'Lean', 'pylon', '2025-11-01T00:00:00Z'),
('lean-4728', 'Multiple receipts upload for a single expense claim', 'is it possible for employees to upload multiple receipts for a single expense claim?', 'pending', 'new_signal', 'Lean', 'pylon', '2025-12-01T00:00:00Z'),
('lean-5110', 'Revert rejected expense back to employee for correction and re-submission', 'is there a way to revert a rejected expense back to the employee to correct and re-submit? or do they need to re-create the expense from scratch', 'pending', 'new_signal', 'Lean', 'pylon', '2026-01-15T00:00:00Z'),
('lean-5067', 'Allow employees to submit expense claims for future dates', 'is there a way to enable employees to submit expense claims for future dates?', 'pending', 'new_signal', 'Lean', 'pylon', '2026-01-13T00:00:00Z'),
('lean-4787', 'Expense review workflow improvements', 'Are there any plans to make the Expenses review process better? Some things I have seen on other platforms that I would love to see here', 'pending', 'new_signal', 'Lean', 'pylon', '2025-12-01T00:00:00Z'),
('lean-4694', 'Bulk compensation update for multiple employees', 'is there a way to do bulk update for compensation?', 'pending', 'new_signal', 'Lean', 'pylon', '2025-12-01T00:00:00Z'),
('lean-3513', 'HiBob and Cercli integration', 'do we have an integration between bob and cercli?', 'pending', 'new_signal', 'Lean', 'pylon', '2025-10-01T00:00:00Z'),
('lean-4610', 'Wafeq accounting integration', 'Wafeq-Cercli Integration Timelines - when can we expect a direct integration with Wafeq for payroll and expense accounting?', 'pending', 'new_signal', 'Lean', 'pylon', '2025-12-01T00:00:00Z'),
('lean-3356', 'KSA payrun summary report in Saudi Riyals (SAR)', 'Can we have a Payrun summary for the KSA payroll that will show in Saudi Riyals? or if theres a way to see amounts in SAR', 'pending', 'new_signal', 'Lean', 'pylon', '2025-10-01T00:00:00Z'),
('lean-5072', 'GPSSA pension scheme integration (similar to GOSI for KSA)', 'can we incorporate GPSSA in the system like what we do in GOSI for KSA?', 'pending', 'new_signal', 'Lean', 'pylon', '2026-01-13T00:00:00Z'),
('lean-1670', 'Outstanding EOSB provision visibility on the platform', 'Is there a way to see the outstanding EOSB provision we should be accounting for on the platform?', 'pending', 'new_signal', 'Lean', 'pylon', '2025-07-01T00:00:00Z'),
('lean-5483', 'Probation period completion notification alerts', 'we stopped getting notifications about employees who are about to complete their probation period. Please add a notification', 'pending', 'new_signal', 'Lean', 'pylon', '2026-01-15T00:00:00Z'),
('lean-5828', 'Admin ability to download payslips on behalf of employees', 'Downloading Payslips on Behalf of Employee - admin requested ability to download employee payslips', 'pending', 'new_signal', 'Lean', 'pylon', '2026-02-15T00:00:00Z'),
('lean-5954', 'TRN number on Cercli invoices', 'Adding TRN number to attached invoices - please add our TRN and correct address in the invoices', 'pending', 'new_signal', 'Lean', 'pylon', '2026-02-20T00:00:00Z'),
('lean-6238', 'Entity-level user role configuration for payroll management', 'Entity-level user role configuration for payroll management - need to configure roles per entity not just globally', 'pending', 'new_signal', 'Lean', 'pylon', '2026-05-10T00:00:00Z'),
('lean-6106', 'Full Egypt payroll support with direct payment (not bank file only)', 'Payroll Compliance and Support in Egypt - right now payments need to be made on our side with Cercli providing the bank file only', 'pending', 'new_signal', 'Lean', 'pylon', '2026-05-01T00:00:00Z'),
('lean-3188', 'ADCB bank integration for direct payroll payouts', 'our ProdEng team is ready to build an integration with ADCB Payouts functionality - Integration request for ADCB Payouts', 'pending', 'new_signal', 'Lean', 'pylon', '2025-09-01T00:00:00Z'),
('lean-nps-1', 'Split expense and salary pay runs into separate runs', 'Splitting Expense and Salary pay runs - right now they are combined and we want them separate', 'pending', 'new_signal', 'Lean', 'pylon', '2026-06-09T00:00:00Z'),
('lean-nps-2', 'Equipment sourcing and procurement for remote employees', 'Equipment sourcing/procurement (especially for remote employees) - this is missing from the platform', 'pending', 'new_signal', 'Lean', 'pylon', '2026-06-09T00:00:00Z'),
('lean-nps-3', 'AI-powered expense review, editing and querying', 'More AI functionality to help review/edit/query expense submissions', 'pending', 'new_signal', 'Lean', 'pylon', '2026-06-09T00:00:00Z')
on conflict (source_id, source) do nothing;
