-- Thndr feature requests from Pylon tickets (CSV export)
-- Only genuine product feature requests extracted (bugs, operational, admin tasks excluded)

INSERT INTO signals (account_name, feature_request, source, source_id, signal_date, category) VALUES
-- From rows 1-53 (prior session)
('Thndr', 'Salary certificate: travel dates as mandatory field', 'pylon', 'thndr-6533', '2026-05-29', NULL),
('Thndr', 'Letters: option to remove disclaimer at end', 'pylon', 'thndr-6527', '2026-05-27', NULL),
('Thndr', 'Bulk onboarding: add employee level field', 'pylon', 'thndr-6526', '2026-05-27', NULL),
('Thndr', 'National ID and EID expiry fields optional; multi-field reports with ID columns', 'pylon', 'thndr-6475', '2026-05-20', NULL),
('Thndr', 'Employee offboarding date history tracking', 'pylon', 'thndr-6255', '2026-05-04', NULL),
('Thndr', 'Manager access to employee basic data (role, department)', 'pylon', 'thndr-6202', '2026-04-28', NULL),
('Thndr', 'Manager access: granular view permissions control', 'pylon', 'thndr-6006', '2026-04-16', NULL),
('Thndr', 'Email notifications: separate copies for manager vs responder', 'pylon', 'thndr-5932', '2026-04-09', NULL),
-- From rows 54-291
('Thndr', 'Document repository with visibility controls (all employees / specific / admins only)', 'pylon', 'thndr-5724', '2026-04-16', NULL),
('Thndr', 'Payroll report: include employee bank IBAN field', 'pylon', 'thndr-5159', '2026-03-14', NULL),
('Thndr', 'Manager access: view employee role and department', 'pylon', 'thndr-4706', '2026-02-15', NULL),
('Thndr', 'Salary history report with full compensation history', 'pylon', 'thndr-4326', '2026-01-27', NULL),
('Thndr', 'Bulk upload/edit for employee data and records', 'pylon', 'thndr-4096', '2026-01-13', NULL),
('Thndr', 'Work permit number: support alphanumeric (letters + numbers) input', 'pylon', 'thndr-3791', '2025-12-23', NULL),
('Thndr', 'Reports: export salary changes and promotions history over time', 'pylon', 'thndr-3648', '2025-12-11', NULL),
('Thndr', 'Bulk document upload for multiple employees at once', 'pylon', 'thndr-3309', '2025-11-18', NULL),
('Thndr', 'Document expiry date field on all document types', 'pylon', 'thndr-3274', '2025-11-17', NULL),
('Thndr', 'Reports: include manager email address (not just name)', 'pylon', 'thndr-3262', '2025-11-13', NULL),
('Thndr', 'Bulk update for employee contract end dates', 'pylon', 'thndr-3102', '2025-10-28', NULL),
('Thndr', 'Reports: downloadable contract end date and hire date columns', 'pylon', 'thndr-3095', '2025-10-28', NULL),
('Thndr', 'Promotion by level only (same role, different level)', 'pylon', 'thndr-2834', '2025-10-13', NULL),
('Thndr', 'Email notification preferences and management', 'pylon', 'thndr-2826', '2025-10-13', NULL),
('Thndr', 'Raw data / API access for custom self-serve reporting', 'pylon', 'thndr-2685', '2025-10-01', NULL),
('Thndr', 'Custom document types (military cert, birth cert, labor doc, etc.)', 'pylon', 'thndr-2631', '2025-09-30', NULL),
('Thndr', 'Custom document names and multiple uploads of same document type', 'pylon', 'thndr-1724', '2025-08-10', NULL),
('Thndr', 'Limited admin role: view and upload documents but no salary access', 'pylon', 'thndr-1544', '2025-07-29', NULL),
('Thndr', 'Employee directory: filter by manager; public profile visibility for all employees', 'pylon', 'thndr-518', '2025-06-02', NULL),
('Thndr', 'Store equity data in Cercli (stock options, vesting schedules)', 'pylon', 'thndr-149', '2025-05-11', NULL),
('Thndr', 'Edit employee general info without mandatory field restrictions', 'pylon', 'thndr-17', '2025-04-29', NULL),
('Thndr', 'Notifications digest: monthly table for contract and probation expiry', 'pylon', 'thndr-3418', '2025-11-24', NULL);

-- Corresponding insight cards for Thndr (shown in the insights sidebar for review)
INSERT INTO insight_cards (related_account, type, title, body, source, status) VALUES
('Thndr', 'new_signal', 'Salary certificate: travel dates as mandatory field', 'Customer requested travel dates be mandatory when issuing salary certificates.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Letters: option to remove disclaimer at end', 'Customers want ability to delete the disclaimer appended at the end of generated letters.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Bulk onboarding: add employee level field', 'Missing level field in bulk onboarding flow — required for structured employee data.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'National ID and EID expiry fields optional; multi-field reports with ID columns', 'Request to make National ID and EID expiry optional, plus ability to add multiple ID fields to reports.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Employee offboarding date history tracking', 'No history view for past offboarding dates — needed for audit and record-keeping.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Manager access to employee basic data (role, department)', 'Managers cannot access basic employee info like role and department through their permission level.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Manager access: granular view permissions control', 'Current manager access lacks granular view permissions — admins cannot fine-tune what managers can see.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Email notifications: separate copies for manager vs responder', 'When notifications are sent, manager and the responding CS rep receive duplicated emails — needs separation.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Document repository with visibility controls (all employees / specific / admins only)', 'Ability to upload policies and templates to Cercli and set who can see them, instead of using Google Drive.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Payroll report: include employee bank IBAN field', 'No way to include bank IBAN in payroll report — needed for reconciliation.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Manager access: view employee role and department', 'Manager trying to configure access to see people role and department found no option available.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Salary history report with full compensation history', 'Need to extract report showing salary history — not currently available.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Bulk upload/edit for employee data and records', 'After performance cycle, need to update salaries, levels, and roles for almost all employees — no bulk option.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Work permit number: support alphanumeric (letters + numbers) input', 'Work permit field only accepts numbers — some permit numbers include letters.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Reports: export salary changes and promotions history over time', 'No way to export a report showing salary changes and job title/promotion history over a defined period.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Bulk document upload for multiple employees at once', 'Currently no bulk document upload — each document must be added one by one.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Document expiry date field on all document types', 'Documents currently only have issuing date — expiry date needed on all document types.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Reports: include manager email address (not just name)', 'Reports show manager name but not email — makes it hard to use data externally.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Bulk update for employee contract end dates', 'Many contracts expired in system but have been renewed — no way to bulk-update end dates.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Reports: downloadable contract end date and hire date columns', 'Contract end date and hire/employment date not available as downloadable columns in reports.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Promotion by level only (same role, different level)', 'Cannot promote employee to a higher level within the same role — system requires role change.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Email notification preferences and management', 'No way to manage or configure which email notifications you receive from Cercli.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Raw data / API access for custom self-serve reporting', 'Request to be able to query raw data directly for custom reporting without going through Cercli team.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Custom document types (military cert, birth cert, labor doc, etc.)', 'Need to add custom document types not in the predefined list — e.g. military certificate, birth certificate.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Custom document names and multiple uploads of same document type', 'Cannot name documents freely or upload two documents of the same type (e.g. two contracts).', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Limited admin role: view and upload documents but no salary access', 'Need a restricted admin that can view employee data and upload documents but cannot see salaries.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Employee directory: filter by manager; public profile visibility for all employees', 'Cannot filter directory by manager. Clicking on employee profile shows permission error — basic info should be visible to all.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Store equity data in Cercli (stock options, vesting schedules)', 'Ability to host custom fields for employee equity: stock options, vesting schedules, etc.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Edit employee general info without mandatory field restrictions', 'Mandatory fields block editing of general info — would like to update partial data without filling all required fields.', 'pylon', 'pending'),
('Thndr', 'new_signal', 'Notifications digest: monthly table for contract and probation expiry', 'Instead of one-by-one notifications, send a monthly digest listing all contracts/probation periods expiring that month.', 'pylon', 'pending');
