export enum EventType {
  // Organization
  ORGANIZATION_CREATED = "ORGANIZATION_CREATED",
  ORGANIZATION_UPDATED = "ORGANIZATION_UPDATED",

  // User
  USER_CREATED = "USER_CREATED",
  USER_UPDATED = "USER_UPDATED",
  USER_DEACTIVATED = "USER_DEACTIVATED",

  // Role
  ROLE_CREATED = "ROLE_CREATED",
  ROLE_UPDATED = "ROLE_UPDATED",
  ROLE_PUBLISHED = "ROLE_PUBLISHED",
  ROLE_CLOSED = "ROLE_CLOSED",
  ROLE_PAUSED = "ROLE_PAUSED",

  // Candidate
  CANDIDATE_CREATED = "CANDIDATE_CREATED",
  CANDIDATE_UPDATED = "CANDIDATE_UPDATED",
  CANDIDATE_MERGED = "CANDIDATE_MERGED",
  CANDIDATE_DO_NOT_CONTACT_SET = "CANDIDATE_DO_NOT_CONTACT_SET",

  // Application
  APPLICATION_CREATED = "APPLICATION_CREATED",
  APPLICATION_STAGE_ADVANCED = "APPLICATION_STAGE_ADVANCED",
  APPLICATION_REJECTED = "APPLICATION_REJECTED",
  APPLICATION_WITHDRAWN = "APPLICATION_WITHDRAWN",
  APPLICATION_HIRED = "APPLICATION_HIRED",

  // Screening
  SCREENING_COMPLETED = "SCREENING_COMPLETED",
  SCREENING_CORRECTION_SUBMITTED = "SCREENING_CORRECTION_SUBMITTED",

  // Interview
  INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED",
  INTERVIEW_RESCHEDULED = "INTERVIEW_RESCHEDULED",
  INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED",
  INTERVIEW_CANCELLED = "INTERVIEW_CANCELLED",

  // Scorecard
  SCORECARD_SUBMITTED = "SCORECARD_SUBMITTED",

  // Message
  MESSAGE_SENT = "MESSAGE_SENT",
  MESSAGE_RECEIVED = "MESSAGE_RECEIVED",
  MESSAGE_DRAFT_CREATED = "MESSAGE_DRAFT_CREATED",

  // Note
  NOTE_WRITTEN = "NOTE_WRITTEN",

  // Agent
  AGENT_TOOL_CALLED = "AGENT_TOOL_CALLED",
  AGENT_SESSION_STARTED = "AGENT_SESSION_STARTED",

  // Sourcing
  SOURCING_CAMPAIGN_STARTED = "SOURCING_CAMPAIGN_STARTED",
  SOURCING_CANDIDATE_INGESTED = "SOURCING_CANDIDATE_INGESTED",

  // Pipeline
  PIPELINE_TEMPLATE_CREATED = "PIPELINE_TEMPLATE_CREATED",
  PIPELINE_STAGE_ADDED = "PIPELINE_STAGE_ADDED",
  PIPELINE_STAGE_REMOVED = "PIPELINE_STAGE_REMOVED",
  PIPELINE_STAGE_REORDERED = "PIPELINE_STAGE_REORDERED",
}
